// Reporter Rankings Data
// This file will be auto-generated by GitHub Actions
// Placeholder data for initial deployment

const REPORTER_DATA = {
  "generated_at": "2025-12-26T00:00:00",
  "total_rumors": 0,
  "total_reporters": 5,
  "reporters": [
    {
      "id": "shams_charania",
      "name": "Shams Charania",
      "outlet": "ESPN",
      "tier": 1,
      "avatar": "SC",
      "total": 0,
      "breaking": 0,
      "by_topic": {},
      "by_player": {},
      "by_team": {},
      "by_date": {},
      "recent_rumors": []
    },
    {
      "id": "marc_stein",
      "name": "Marc Stein",
      "outlet": "The Stein Line",
      "tier": 1,
      "avatar": "MS",
      "total": 0,
      "breaking": 0,
      "by_topic": {},
      "by_player": {},
      "by_team": {},
      "by_date": {},
      "recent_rumors": []
    },
    {
      "id": "jake_fischer",
      "name": "Jake Fischer",
      "outlet": "Yahoo Sports",
      "tier": 1,
      "avatar": "JF",
      "total": 0,
      "breaking": 0,
      "by_topic": {},
      "by_player": {},
      "by_team": {},
      "by_date": {},
      "recent_rumors": []
    },
    {
      "id": "chris_haynes",
      "name": "Chris Haynes",
      "outlet": "Bleacher Report",
      "tier": 1,
      "avatar": "CH",
      "total": 0,
      "breaking": 0,
      "by_topic": {},
      "by_player": {},
      "by_team": {},
      "by_date": {},
      "recent_rumors": []
    },
    {
      "id": "brian_windhorst",
      "name": "Brian Windhorst",
      "outlet": "ESPN",
      "tier": 2,
      "avatar": "BW",
      "total": 0,
      "breaking": 0,
      "by_topic": {},
      "by_player": {},
      "by_team": {},
      "by_date": {},
      "recent_rumors": []
    }
  ],
  "rumors": [],
  "note": "This is placeholder data. Run the GitHub Action to generate real data from the Rumors Archive."
};

// Export for use in HTML
if (typeof window !== 'undefined') {
    window.REPORTER_DATA = REPORTER_DATA;
}
